USE [master]
GO

CREATE DATABASE [Consulting]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Consulting',  SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Consulting_log', SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Consulting].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Consulting] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Consulting] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Consulting] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Consulting] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Consulting] SET ARITHABORT OFF 
GO

ALTER DATABASE [Consulting] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Consulting] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Consulting] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Consulting] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Consulting] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Consulting] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Consulting] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Consulting] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Consulting] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Consulting] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Consulting] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Consulting] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Consulting] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Consulting] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Consulting] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Consulting] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Consulting] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Consulting] SET RECOVERY FULL 
GO

ALTER DATABASE [Consulting] SET  MULTI_USER 
GO

ALTER DATABASE [Consulting] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Consulting] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Consulting] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Consulting] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Consulting] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Consulting] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Consulting] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Consulting] SET  READ_WRITE 
GO


